### ISSUE TITLE
Can't use Pico on Arduino IDE

### ISSUE THREAD

**Issue by Marcin84-dev** [Xinyuan-LilyGO/T-PicoC3#25]
I have errors like this:
Arduino:1.8.19 (Linux), Płytka:"ESP32C3 Dev Module, Disabled, Default 4MB with spiffs (1.2MB APP/1.5MB SPIFFS), 160MHz (WiFi), QIO, 80MHz, 4MB (32Mb), 921600, None, Enabled"

Traceback (most recent call last):
  File "/home/marcin/.arduino15/packages/esp32/tools/esptool_py/4.2.1/esptool.py", line 31, in <module>
    import esptool
  File "/home/marcin/.arduino15/packages/esp32/tools/esptool_py/4.2.1/esptool/__init__.py", line 42, in <module>
    from esptool.cmds import (
  File "/home/marcin/.arduino15/packages/esp32/tools/esptool_py/4.2.1/esptool/cmds.py", line 14, in <module>
    from .bin_image import ELFFile, ImageSegment, LoadFirmwareImage
  File "/home/marcin/.arduino15/packages/esp32/tools/esptool_py/4.2.1/esptool/bin_image.py", line 14, in <module>
    from .loader import ESPLoader
  File "/home/marcin/.arduino15/packages/esp32/tools/esptool_py/4.2.1/esptool/loader.py", line 21, in <module>
    import serial
ModuleNotFoundError: No module named 'serial'
exit status 1
Błąd kompilacji dla płytki ESP32C3 Dev Module.

What can i do?

**Comment by archimere** [comment]
Hello,

I Have the same problème to some attachement. Can't any one help us ?
My #include "pico/stdlib.h" dosen't finf ??
No Tft_espi is work to :( 

Could'I find some help of the community  please !
